routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin','middleware' => 'auth'], function(){
    Route::get('/','Admin\DashboardController@index');
    Route::resource('/kategori', 'Admin\KategoriController');
    Route::resource('/tugas', 'Admin\TugasController');
    Route::resource('/roles', 'Admin\RoleController');
    Route::resource('/users', 'Admin\UserController');
    
});

app/Http/Controllers/API/Tugas/TugasController.php
<?php

namespace App\Http\Controllers\API\Tugas;

use App\Http\Controllers\Controller;
use App\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TugasController extends Controller
{
    //
    public function getAll()
    {
        $data = DB::table('tasks')
            ->orderBy('id', 'desc')
            ->get();
        return response()->json($data, 200);
    }

    public function store(Request $request)
    {
        $validateData = $request->validate([
            'id' => 'required',
            'nama_tugas' => 'required',
            'id_kategori' => 'required',
            'ket_tugas' => 'required',
            'status_tugas' => 'required',
        ]);

        $data = new Task;
        $data->id = $request->id;
        $data->nama_tugas = $request->nama_tugas;
        $data->id_kategori = $request->id_kategori;
        $data->ket_tugas = $request->ket_tugas;
        $data->status_tugas = $request->status_tugas;
        $data->save();

        return response()->json($data, 201);
    }

    public function update(Request $request)
    {
        $validateData = $request->validate([
            'id' => 'required',
            'nama_tugas' => 'required',
            'id_kategori' => 'required',
            'ket_tugas' => 'required',
            'status_tugas' => 'required',
        ]);

        $data = Task::where('id', '=', $request->id)->first();
        $data->id = $request->id;
        $data->nama_tugas = $request->nama_tugas;
        $data->id_kategori = $request->id_kategori;
        $data->ket_tugas = $request->ket_tugas;
        $data->status_tugas = $request->status_tugas;
        $data->save();

        return response()->json($data, 201);
    }

    public function destroy(Request $request)
    {
        $data = Task::where('id', '=', $request->id)->first();

        if (!empty($data)) {
            $data->delete();

            return response()->json($data, 200);
        } else {
            return response()->json([
                'error' => 'data tidak ditemukan',
            ], 404);
        }
    }
}

app/Http/Controllers/Admin/TugasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\kategori;
use Illuminate\Http\Request;
use App\Task;

class TugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    function __construct(){
        // $this->middleware('role:admin|manajer');
        // $this->middleware('role:karyawan',['only'=>'index']);

        $this->middleware('permission:tugas-list',['only'=>['index']]);
        $this->middleware('permission:tugas-create',['only'=>['create','store']]);
        $this->middleware('permission:tugas-edit',['only'=>['edit','update']]);
        $this->middleware('permission:tugas-delete',['only'=>['destroy']]);
    }


    public function index()
    {
        //
        //
        $pagename='Data Tugas';
        $data=Task::all();
        return view('admin.tugas.index', compact('data', 'pagename')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data_kategori = kategori::all();
        $pagename = 'Form Input Tugas';
        return view('admin.tugas.create', compact('pagename', 'data_kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'txtnama_tugas' => 'required',
            'optionid_kategori' => 'required',
            'txtketerangan_tugas' => 'required',
            'radiostatus_tugas' => 'required',
        ]);

        $data_tugas = new Task([
            'nama_tugas' => $request->get('txtnama_tugas'),
            'id_kategori' => $request->get('optionid_kategori'),
            'ket_tugas' => $request->get('txtketerangan_tugas'),
            'status_tugas' => $request->get('radiostatus_tugas'),
        ]);

        $data_tugas->save();
        return redirect('admin/tugas')->with('Sukses', 'Tugas Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data_kategori=kategori::all();
        $pagename='Update Tugas';
        $data=Task::find($id);
        return view('admin.tugas.edit', compact('data', 'pagename', 'data_kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'txtnama_tugas' => 'required',
            'optionid_kategori' => 'required',
            'txtketerangan_tugas' => 'required',
            'radiostatus_tugas' => 'required',
        ]);

        $tugas = Task::find($id);
            $tugas->nama_tugas = $request->get('txtnama_tugas');
            $tugas->id_kategori = $request->get('optionid_kategori');
            $tugas->ket_tugas = $request->get('txtketerangan_tugas');
            $tugas->status_tugas = $request->get('radiostatus_tugas');

        $tugas->save();
        return redirect('admin/tugas')->with('Sukses', 'Tugas Berhasil DiUpdate');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $tugas = Task::find($id);
        
        $tugas->delete();
        return redirect('admin/tugas')->with('Sukses', 'Tugas Berhasil DiHapus');
    }
}

resources/views/admin/tugas/create.blade.php
@extends('admin.layout.master')

@section('content')

    <link rel="stylesheet" href="{{asset('public/vendors/bootstrap/dist/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/font-awesome/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/themify-icons/css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/selectFX/css/cs-skin-elastic.css')}}">

    <link rel="stylesheet" href="{{asset('public/assets/css/style.css')}}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

<div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Dashboard</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Dashboard</a></li>
                            <li><a href="#">Forms</a></li>
                            <li class="active">Basic</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mt-3">
            <div class="animated fadeIn">

                                            <div class="col-lg-12">
                                                <div class="card">
                                                    <div class="card-header">
                                                        <strong>{{$pagename}}</strong>
                                                    </div>
                                                    <div class="card-body card-block">

                                                        @if($errors->any())
                                                            <div class="alert alert-danger">
                                                                <div class="list-group">
                                                                @foreach($errors->all() as $error)
                                                                    <li class="list-group-item">
                                                                        {{$error}}
                                                                    </li>
                                                                    @endforeach
                                                                </div>
                                                            </div>

                                                         @endif

                                                        <form action="{{route('tugas.store')}}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                                            @csrf
                                                        <div class="row form-group">
                                                                <div class="col col-md-3"><label for="text-input" class=" form-control-label">Nama Tugas</label></div>
                                                                <div class="col-12 col-md-9"><input type="text" id="text-input" name="txtnama_tugas" placeholder="Text" class="form-control"><small class="form-text text-muted">This is a help text</small></div>
                                                            </div>
                                                                <div class="row form-group">
                                                                    <div class="col col-md-3"><label for="select" class=" form-control-label">Kategori Tugas</label></div>
                                                                    <div class="col-12 col-md-9">
                                                                        <select name="optionid_kategori" id="select" class="form-control">

                                                                            @foreach($data_kategori as $kategori)

                                                                            <option value= {{$kategori->id}}>
                                                                                {{$kategori->nama_kategori}}</option>

                                                                            @endforeach

                                                                        </select>
                                                                    </div>
                                                                </div>

                                                                <div class="row form-group">
                                                                <div class="col col-md-3"><label for="text-input" class=" form-control-label">Keterangan Tugas</label></div>
                                                                <div class="col-12 col-md-9"><input type="text" id="text-input" name="txtketerangan_tugas" placeholder="Text" class="form-control"><small class="form-text text-muted">This is a help text</small></div>
                                                            </div>

                                                               
                                                                <div class="row form-group">
                                                                    <div class="col col-md-3"><label class=" form-control-label">Status Tugas</label></div>
                                                                    <div class="col col-md-9">
                                                                        <div class="form-check-inline form-check">
                                                                            <label for="inline-radio1" class="form-check-label ">
                                                                                <input type="radio" id="inline-radio1" name="radiostatus_tugas" value="0" class="form-check-input">Masih Berjalan
                                                                            </label>
                                                                            <label for="inline-radio2" class="form-check-label ">
                                                                                <input type="radio" id="inline-radio2" name="radiostatus_tugas" value="1" class="form-check-input">Selesai
                                                                            </label>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                        <button type="submit" class="btn btn-primary btn-sm">
                                                            <i class="fa fa-dot-circle-o"></i> Simpan
                                                        </button>
                                                        <button type="reset" class="btn btn-danger btn-sm">
                                                            <i class="fa fa-ban"></i> Reset
                                                        </button>
                                                        </form>
                                                    </div>
                                                    
                                                </div>
                        
                                          
                                        </div><!-- .animated -->
                                    </div><!-- .content -->

                            <script src="{{asset('public/vendors/jquery/dist/jquery.min.js')}}"></script>
                            <script src="{{asset('public/vendors/popper.js/dist/umd/popper.min.js')}}"></script>

                            <script src="{{asset('public/vendors/jquery-validation/dist/jquery.validate.min.js')}}"></script>
                            <script src="{{asset('public/vendors/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js')}}"></script>

                            <script src="{{asset('public/vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
                            <script src="{{asset('public/assets/js/main.js')}}"></script>

@endsection

resources/views/admin/tugas/edit.blade.php
@extends('admin.layout.master')

@section('content')

    <link rel="stylesheet" href="{{asset('public/vendors/bootstrap/dist/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/font-awesome/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/themify-icons/css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/selectFX/css/cs-skin-elastic.css')}}">

    <link rel="stylesheet" href="{{asset('public/assets/css/style.css')}}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Forms</a></li>
                    <li class="active">Basic</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body card-block">                
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <strong>{{ $pagename }}</strong>
                            </div>
                            <div class="card-body card-block">

                                @if ($errors->any())
                                <div class="alert alert-danger">
                                    <div class="list-group">
                                        @foreach ($errors->all() as $error)
                                           <li class="list-group-item">
                                               {{ $error }}
                                           </li> 
                                        @endforeach
                                    </div>
                                </div>
                                @endif

                                <form action="{{ route('tugas.update', $data->id) }}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    @method('PATCH')
                                    @csrf
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Nama Tugas</label></div>
                                        <div class="col-12 col-md-9"><input type="text" id="text-input" name="txtnama_tugas" value="{{ $data->nama_tugas }}" placeholder="Text" class="form-control"><small class="form-text text-muted">This is a help text</small></div>
                                    </div>
                                        <div class="row form-group">
                                            <div class="col col-md-3"><label for="select" class=" form-control-label">Kategori Tugas</label></div>
                                            <div class="col-12 col-md-9">
                                                <select name="optionid_kategori" id="select" class="form-control">
                                                    
                                                    @foreach ($data_kategori as $kategori )
                                                    <option value={{ $kategori->id}}
                                                        @if ($kategori->id==$data->id_kategori)
                                                        selected 
                                                        @endif
                                                    >
                                                    {{ $kategori->nama_kategori }}</option>
                                                    @endforeach
                                                    
                                                </select>
                                            </div>
                                        </div>
                                        <div class="row form-group">
                                            <div class="col col-md-3"><label for="text-input" class=" form-control-label">Keterangan Tugas</label></div>
                                            <div class="col-12 col-md-9"><input type="text" id="text-input" name="txtketerangan_tugas" value="{{ $data->ket_tugas }}" placeholder="Text" class="form-control"><small class="form-text text-muted">This is a help text</small></div>
                                        </div>
                                        <div class="row form-group">
                                            <div class="col col-md-3"><label class=" form-control-label">Status Tugas</label></div>
                                            <div class="col col-md-9">
                                                <div class="form-check-inline form-check">
                                                    <label for="inline-radio1" class="form-check-label ">
                                                        <input type="radio" id="inline-radio1" name="radiostatus_tugas" value=0 {{ $data->status_tugas==0?'checked':'' }} class="form-check-input">Masih Berjalan
                                                    </label>
                                                    <label for="inline-radio2" class="form-check-label ">
                                                        <input type="radio" id="inline-radio2" name="radiostatus_tugas" value=1 {{ $data->status_tugas==1?'checked':'' }} class="form-check-input">Selesai
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                            <button type="submit" class="btn btn-primary btn-sm">
                                                <i class="fa fa-dot-circle-o"></i> Update
                                            </button>
                                            <button type="reset" class="btn btn-danger btn-sm">
                                                <i class="fa fa-ban"></i> Reset
                                            </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div><!-- .animated -->
</div><!-- .content -->


                            <script src="{{asset('public/vendors/jquery/dist/jquery.min.js')}}"></script>
                            <script src="{{asset('public/vendors/popper.js/dist/umd/popper.min.js')}}"></script>

                            <script src="{{asset('public/vendors/jquery-validation/dist/jquery.validate.min.js')}}"></script>
                            <script src="{{asset('public/vendors/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js')}}"></script>

                            <script src="{{asset('public/vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
                            <script src="{{asset('public/assets/js/main.js')}}"></script>

@endsection

resources/views/admin/tugas/index.blade.php
@extends('admin.layout.master')

@section('content')

    <link rel="stylesheet" href="{{asset('public/vendors/bootstrap/dist/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/font-awesome/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/themify-icons/css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/selectFX/css/cs-skin-elastic.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/datatables.net-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/vendors/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css')}}">

    <link rel="stylesheet" href="{{asset('public/assets/css/style.css')}}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Table</a></li>
                    <li class="active">Data table</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">

            <div class="col-md-12">
                <div class="card">

                    @if (session()->get('Sukses'))
                    <div class="alert alert-success">
                        {{ session()->get('Sukses') }}

                    </div>
                        
                    @endif

                    <div class="card-header">
                        <strong class="card-title">{{ $pagename }}</strong>
                        @can('tugas-create')
                        <a href="{{ route('tugas.create') }}" class="btn btn-primary pull-right">Tambah</a>
                        @endcan
                    </div>
                    <div class="card-body">
                        <table id="bootstrap-data-table-export" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama</th>
                                    <th>Kategori</th>
                                    <th>Keterangan</th>
                                    <th>Status</th>
                                    @can('tugas')
                                    <th>Edit</th>
                                    <th>Hapus</th>
                                    @endcan
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($data as $i=>$row )
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $row->nama_tugas }}</td>
                                    <td>{{ $row->id_kategori }}</td>
                                    <td>{{ $row->ket_tugas }}</td>
                                    <td>{{ $row->status_tugas }}</td>
                                    @can('tugas-edit')
                                    <td><a href="{{ route('tugas.edit', $row->id) }}" class="btn btn-primary">Edit</a></td>
                                    @endcan
                                    @can('tugas-delete')
                                    <td>
                                        <form action="{{ route('tugas.destroy', $row->id) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">Hapus</button>
                                        </form>
                                    </td>
                                    @endcan
                                </tr>
                                    
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


        </div>
    </div><!-- .animated -->
</div><!-- .content -->

    <script src="{{asset('public/vendors/jquery/dist/jquery.min.js')}}"></script>
    <script src="{{asset('public/vendors/popper.js/dist/umd/popper.min.js')}}"></script>
    <script src="{{asset('public/vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('public/assets/js/main.js')}}"></script>


    <script src="{{asset('public/vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('public/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('public/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('public/vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('public/vendors/jszip/dist/jszip.min.js')}}"></script>
    <script src="{{asset('public/vendors/pdfmake/build/pdfmake.min.js')}}"></script>
    <script src="{{asset('public/vendors/pdfmake/build/vfs_fonts.js')}}"></script>
    <script src="{{asset('public/vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('public/vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('public/vendors/datatables.net-buttons/js/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('public/assets/js/init-scripts/data-table/datatables-init.js')}}"></script>

@endsection